version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "dagster"
      MYSQL_USER: "dagster"
      MYSQL_PASSWORD: "dagstersecret"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"

volumes:
  db:
