FROM python:3.12-slim

RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app

WORKDIR /opt/dagster/app

COPY pyproject.toml data/ /opt/dagster/app/

RUN pip install poetry && poetry install

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

EXPOSE 4444

ENTRYPOINT ["poetry", "run", "dagster", "api", "gprc", "-h", "0.0.0.0", "-p", "4444", "--module-name", "data"]
